package model;//package model;
//
//public enum Country {
//    ALBANIA,
//    ANDORRA,
//    AUSTRIA,
//    BELGIUM,
//    BELARUS,
//    BOSNIA_AND_HERZEGOVINA,
//    BULGARIA,
//    CROATIA,
//    MONTENEGRO,
//    CYPRUS,
//    CZECH,
//    DENMARK,
//    ESTONIA,
//    FINLAND,
//    FRANCE,
//    GREECE,
//    SPAIN,
//    NETHERLANDS,
//    IRELAND,
//    ICELAND,
//    KOSOVO,
//    LITHUANIA,
//    LUXEMBOURG,
//    LATVIA,
//    MACEDONIA,
//    MALTA,
//    MOLDOVA,
//    MONACO,
//    GERMANY,
//    NORWAY,
//    POLAND,
//    PORTUGAL,
//    ROMANIA,
//    SAN_MARINO,
//    SERBIA,
//    SLOVAKIA,
//    SLOVENIA,
//    SWITZERLAND,
//    SWEDEN,
//    UKRAINE,
//    HUNGARY,
//    UNITED_KINGDOM,
//    ITALY,
//
//}